### ISSUE TITLE
Milestone 2 Checklist

### ISSUE THREAD

**Issue by Lussier115** [aa-software2112/SOEN_344#132]
- [x] Add clinic table in db
- [x] Add clinic_jd for patient, doctor, nurse, availability tables.
- [x]  Register users with clinic id:  
- [x]  Login and store the clinic id in the user objects
- [x] View only availabilities for the patient's specific clinic 
- [x] Create availability with the doctors clinic_id
- [x] Make sure Nurses can only update patients booking for which the patient is eligible.
          - ex: The nurse has to change the booking to another, it must make sure it is in the right clinic.
- [x] Add Clinic page for Admin users.

-------------------------------
Make sure the code you implemented before is still functional 
- [x] @Lussier115 
- [x] @lkadian 
- [ ] @samgo1 
- [ ] @laurawheatley 
- [x] @aa-software2112 
- [x] @KrishnaPatel1 

users: doctor, nurse, patient
