### ISSUE TITLE
Front End: Availability/Appointment/Booking Viewer

### ISSUE THREAD

**Issue by aa-software2112** [aa-software2112/SOEN_344#49]
- [ ] Update Doctor's Availability #93 @Lussier115 
- [ ] Cancel Availability #93 @Lussier115 
- [ ] View Availability #93 @Lussier115 
- [ ] Make Annual and Walk-in Appointment
- [ ] Update/Cancel Appointment
